### ISSUE TITLE
netlify에 gostrim.org 도메인 연결

### ISSUE THREAD

**Issue by beewee22** [gostrim/gostrim.github.io#9]
Netlify로 gostrim.org 를 배포하려고 합니다. 
도메인 제공자로부터 아래의 ANAME 설정이 필요합니다.

`gostrim.org ALIAS vigorous-mirzakhani-d33aeb.netlify.app.`

--- or ---

`gostrim.org A 104.198.14.52`

작업이 완료되시거나 작업을 시작하시려고 하는 경우, 연동 확인이 필요하니 저에게 연락을 부탁드립니다.

**Comment by protess** [comment]
A record 를 위의 아이피로 업데이트 했습니다.
